name = "worker-gateway-template"
main = "worker.js"
compatibility_date = "2026-03-15"
workers_dev = false

# Deploy with this file only for ad-hoc testing.
# For production, copy this file (or use wrangler.<env>.toml)
# with a unique worker name + route binding per domain.
routes = [
]

[vars]
ROUTE_PREFIX = "/json"
ORIGIN_BASE = "https://api.hudie123.xyz;https://vpn2.hudie123.xyz;https://hudie2.an1688.com;https://api2.an1688.com"
ORIGIN_SUB_PATH_PREFIX = "/json"
